### ISSUE TITLE
Not working anymore 

### ISSUE THREAD

**Issue by riyadmondol2006** [buttercookie42/DisableTargetAPIBlock#1]

**Comment by buttercookie42** [comment]
I need a bit more details than that – which app were you trying to install, on what phone, which Android version (regular 14, or one of the QPR betas), etc.

**Comment by riyadmondol2006** [comment]
it's one of the beta

**Comment by buttercookie42** [comment]
_Which_ Beta? And does that mean it used to work, and it stopped working precisely after you upgraded your phone?

**Comment by riyadmondol2006** [comment]
AP11.231117.006

**Comment by buttercookie42** [comment]
Okay, so Android 14 QPR2 Beta 2. I've found a device dump of that, but I don't see any immediate obvious changes, and Google hasn't published the sources yet. Are there any errors in the LSposed logs?

**Comment by buttercookie42** [comment]
Please re-open if you can provide some more useful information.
