### ISSUE TITLE
Can't open

### ISSUE THREAD

**Issue by Arvz-y** [buttercookie42/DisableTargetAPIBlock#11]
I have downloaded and installed the app but the app doesn't appear in my main screen so I can't open it to finish the other steps.

**Comment by Arvz-y** [comment]
> What other steps? This is an Xposed module, there isn't any UI. Just enable the module for the system framework and that's that.

I can't enable the module, I've been finding where can I eneble it and still no luck.

**Comment by buttercookie42** [comment]
This is what it should look like:
![screen](https://github.com/user-attachments/assets/6efa0f58-0bfc-476d-b516-06c4d10995b9)

**Comment by Arvz-y** [comment]
> This is what it should look like: ![screen](https://private-user-images.githubusercontent.com/7611366/383743889-6efa0f58-0bfc-476d-b516-06c4d10995b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MzIwNDMsIm5iZiI6MTczMDkzMTc0MywicGF0aCI6Ii83NjExMzY2LzM4Mzc0Mzg4OS02ZWZhMGY1OC0wYmZjLTQ3NmQtYjUxNi0wNmM0ZDEwOTk1YjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDZUMjIyMjIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQ2MTJkZjRjYWExMzYwMzg2ZjQyMzE1M2RhODc2NTJlMTg3OGQ2NDc3OGIwM2RlOGYxZTAyMGIwNDg3MjBiMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-vcLre8NoxMD72INro-4am67VNVz7K6I7kEc-MzKqls)

So I still need to root my phone and install Ls? Right?

**Comment by buttercookie42** [comment]
Yes.

If you want something that doesn't need root and LSposed, you need to manually install those apps via ADB, or alternatively you could try https://github.com/zacharee/InstallWithOptions, which only needs Shizuku, though note that I haven't tested that app.

**Comment by Arvz-y** [comment]
> Yes.
> 
> If you want something that doesn't need root and LSposed, you need to manually install those old apps via ADB, or alternatively you could try https://github.com/zacharee/InstallWithOptions, which only needs Shizuku, though note that I haven't tested that app.

I'd rather stick to the ones that are trusted. Thanks
