### ISSUE TITLE
not working with android 14 hyperos 1.0.3.0 

### ISSUE THREAD

**Issue by ACHAL-SAYEE** [buttercookie42/DisableTargetAPIBlock#4]
not working with android 14 hyperos 1.0.3.0 for app  https://apkpure.net/sherlock-holmes-lost-detective/com.otherguys.lostdetective/download

**Comment by Nandodina** [comment]
aplikasi

**Comment by buttercookie42** [comment]
What phone model are you using? Are you sure your phone still supports 32-bit apps?

For a test, does https://f-droid.org/packages/info.staticfree.android.units/ fail to install, too?

**Comment by ACHAL-SAYEE** [comment]
This app installed it seems issue with 32 bit app
