### ISSUE TITLE
Not working with Lspatch API version 93

### ISSUE THREAD

**Issue by NictheGreek** [buttercookie42/DisableTargetAPIBlock#5]
Installed the apk to use with lspatch to install old apk of game "Lair Defense: Shrine". Android 14. This patch only works up to API 82.
Still get error message saying apk not compatible with device and refuses to install.

**Comment by buttercookie42** [comment]
This module needs to be applied to the system framework, so if I correctly understand the way Lspatch is supposed to work, it won't work. Patching the APK you want to install won't achieve anything.
