### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by IzzySoft** [buttercookie42/DisableTargetAPIBlock#6]
At IzzyOnDroid we support [Reproducible Builds](https://reproducible-builds.org/) (see: [Reproducible Builds, special client support and more in our repo](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)). Trying for yours, I was able to successfully generate the APK using `./gradlew assembleRelease`, but the resulting APKs were not identical. Your APK misses some files present in the repo here:

```diff
--- /dev/fd/63  2024-06-24 23:57:20.707539045 +0200
+++ /dev/fd/62  2024-06-24 23:57:20.707539045 +0200
@@ -10,9 +10,19 @@
   32-bit CRC value (hex):                         f35e1368
   res/mipmap-anydpi-v26/ic_launcher.xml
   32-bit CRC value (hex):                         18959dd3
+  res/mipmap-hdpi-v4/ic_launcher.webp
+  32-bit CRC value (hex):                         726105db
+  res/mipmap-mdpi-v4/ic_launcher.webp
+  32-bit CRC value (hex):                         ad08b444
+  res/mipmap-xhdpi-v4/ic_launcher.webp
+  32-bit CRC value (hex):                         fe60d158
+  res/mipmap-xxhdpi-v4/ic_launcher.webp
+  32-bit CRC value (hex):                         12e67cde
+  res/mipmap-xxxhdpi-v4/ic_launcher.webp
+  32-bit CRC value (hex):                         099ea624
   res/xml/backup_rules.xml
   32-bit CRC value (hex):                         4cb358b3
   res/xml/data_extraction_rules.xml
   32-bit CRC value (hex):                         4eed8bf6
   resources.arsc
-  32-bit CRC value (hex):                         677c8a61
+  32-bit CRC value (hex):                         ef89ad1f
```

We'd appreciate if you could help making your build reproducible. We've prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that.

Looking forward to your reply!

cc @obfusk

**Comment by obfusk** [comment]
@IzzySoft is it RB if you `rm app/src/main/res/*/ic_launcher.webp` in the recipe?

**Comment by IzzySoft** [comment]
I can test that, give me a few minutes…

**Comment by IzzySoft** [comment]
Sorry, was called away… So: Yes, with that it's RB.

**Comment by IzzySoft** [comment]
@buttercookie42 Can you please take care to have that fixed with the next release? For now, we'll remove those images in the recipe of the verification builder – but that's a little dirty :wink: Thanks!

**Comment by buttercookie42** [comment]
Yes, it seems that I forgot to commit me deleting the old default app icons.

**Comment by IzzySoft** [comment]
Then here comes the good news. Watch out for the green shield:

![image](https://github.com/user-attachments/assets/07736ca3-2131-485f-9103-2874694d2aac)

Ended with an "oops" for `DEPENDENCY_INFO_BLOCK`. So when cleaning up the images, could you also "polish" the `build.gradle.kts` a little?

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

And for a happy ending, let me share the welcome toot with a shared milestone:

![image](https://github.com/user-attachments/assets/7b72c6c2-0bb9-4317-b6f4-755a31e90749)

:star_struck:

**Comment by buttercookie42** [comment]
Hopefully with 1.0.1 everything works as it should?

**Comment by IzzySoft** [comment]
Let's check…

```
$ iod repo get de.buttercookie.disabletargetapiblock
de.buttercookie.disabletargetapiblock: looking for 'https://api.github.com/repos/buttercookie42/DisableTargetAPIBlock/releases'
de.buttercookie.disabletargetapiblock: checking tag '1.0.1'
de.buttercookie.disabletargetapiblock: lastRelNo set to '1.0.1', checking for files
de.buttercookie.disabletargetapiblock: Upstream file date (2024-08-20 21:34) is newer than ours (2023-12-30 01:39).
de.buttercookie.disabletargetapiblock: returning ['1.0.1','https://github.com/buttercookie42/DisableTargetAPIBlock/releases/download/1.0.1/de.buttercookie.disabletargetapiblock-1.0.1.apk',1724182447]
de.buttercookie.disabletargetapiblock: 1.0.0/1.0.1, https://github.com/buttercookie42/DisableTargetAPIBlock/releases: https://github.com/buttercookie42/DisableTargetAPIBlock/releases/download/1.0.1/de.buttercookie.disabletargetapiblock-1.0.1.apk
- Grabbing update for de.buttercookie.disabletargetapiblock: OK
- Checking 'repo/de.buttercookie.disabletargetapiblock_3.apk' for libraries and malware …
- Checking the app's AndroidManifest.xml …
de.buttercookie.disabletargetapiblock: check if repo contains FUNDING.yml
de.buttercookie.disabletargetapiblock: looking for 'https://api.github.com/repos/buttercookie42/DisableTargetAPIBlock/contents/.github'
de.buttercookie.disabletargetapiblock: looking for 'https://api.github.com/repos/buttercookie42/DisableTargetAPIBlock/contents/'
de.buttercookie.disabletargetapiblock: looking for 'https://api.github.com/repos/buttercookie42/.github/contents/'
de.buttercookie.disabletargetapiblock: Github reports "Not Found" for https://api.github.com/repos/buttercookie42/.github/contents/
de.buttercookie.disabletargetapiblock: no FUNDING.yml detected.
de.buttercookie.disabletargetapiblock: no Fastlane configured, skipping Fastlane check.
```

Scanners say all fine. Now, what does the verification builder say?

```
--- END BUILD LOG ---
Keeping '1e500b6367d06b11c056d8564c514105d2d75c4d690b7ff17038daebbc371185-de.buttercookie.disabletargetapiblock-1.0.1-upstream.apk'...
Keeping '6e24951c101467026c3725aafddf2293e5509459c367e8c4fcea25f8aa2285a2-de.buttercookie.disabletargetapiblock-1.0.1-unsigned.apk'...
Reproducible: True
```

All fine, thanks!

Ps: should you wonder about the two things "not detected/found" in the first block:

* [FUNDING.yml](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository)
* [IzzyOnDroid Fastlane Documentation](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane)

Setting up the latter is highly recommended. If you want a "starter package", just say so and I'll send in a PR :smiley:
